# Generated by Django 6.0.1 on 2026-02-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='averageReview',
            field=models.FloatField(default=0),
        ),
    ]
