# Generated by Django 6.0.1 on 2026-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_averagereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='averageReview',
            field=models.FloatField(default=0, null=True),
        ),
    ]
