# Generated by Django 6.0.1 on 2026-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('category_description', models.TextField(max_length=255)),
                ('category_image', models.ImageField(upload_to='photos/category')),
            ],
            options={
                'verbose_name': 'categroy',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
